### ISSUE TITLE
how to add empty directory without real fs?

### ISSUE THREAD

**Issue by uaex** [OlehKulykov/PLzmaSDK#11]

**Comment by uaex** [comment]
also empty file data can not be added by plzma_in_stream_create_with_memory_copy

**Comment by OlehKulykov** [comment]
Not possible, but it's a good idea.

**Comment by uaex** [comment]
empy directory and empy file actually exist sometime 🤔, so can you support it? @OlehKulykov

**Comment by uaex** [comment]
finally I choose libarchive 😂 it is built in macOS
