### ISSUE TITLE
Why PLzmaSDK is much more slower than LzmaSDKObjC

### ISSUE THREAD

**Issue by woshiccm** [OlehKulykov/PLzmaSDK#12]
When I unzip a 7z file, PLzmaSDK takes about 20s, LzmaSDKObjC takes about 6s, why?

**Comment by OlehKulykov** [comment]
- Correct exception handling
- Full thread safe code
- Correct unicode <-> utf8 conversion
- Extra decode delegation args
- Mem secure path handling
