### ISSUE TITLE
Can't use it in android kotlin

### ISSUE THREAD

**Issue by ShKhan9** [OlehKulykov/PLzmaSDK#14]
I read docs here only this line
cd <PATH_TO_ANDROID_NDK>./ndk-build NDK_PROJECT_PATH=<PATH_TO_PLZMASDK>/PLzmaSDK/android

for android ? please add a detailed demo i don't know how to use the library with android kotlin.

**Comment by OlehKulykov** [comment]
Hi Beep Beep/ShKhan9,
I've provided for Android the option - how to compile & use this lib within the native, low level, unmanaged C/C++ env., the rest is for You(Java-To-JNI, and/or Kotlin wrapper).
Sorry, I'm not an Android dev. & I would like to take an aside of any bit-code env.
P.S.: You have an idea of native functionality - the rest up to You.
