### ISSUE TITLE
Detect password protected files

### ISSUE THREAD

**Issue by AnukritiJain19** [OlehKulykov/PLzmaSDK#15]
How can i detect a password protected file ? 

Can you suggest a way to handle the password protected files. The exception description says "can't open in archive". 
I am extracting the file and checking that, if it is not getting extracted then displaying a "enter password" prompt. But if it is not getting extracted for some other reason , then how can i know ?

Any API available for Password Protected files other than setPassword() ?

**Comment by OlehKulykov** [comment]
Hi,
you can't detect if it's a password-protected archive, you should know it(!!!), to avoid brute force attack within this lib/framework. This is an idea of this repo.

**Comment by ezwardChou** [comment]
Hi, is there an indirect way to tell if a file is password protected?

**Comment by OlehKulykov** [comment]
Hi, also no.
