### ISSUE TITLE
Duplicated files

### ISSUE THREAD

**Issue by levinli303** [OlehKulykov/PLzmaSDK#16]
There are two München.jpg in test_files

![Screen Shot 2022-09-06 at 15 43 33](https://user-images.githubusercontent.com/17924287/188576329-289587d6-64fe-4413-8b4d-2f316621c2cc.png)

**Comment by OlehKulykov** [comment]
Hi,
thanks for the note & I've found where is an issue.
In this case, the naming of extra chars depends on type of file system, file explorer, keyboard layout, region settings, etc.

In a different combinations, a newly created file(git status) could be named differently:
- "test_files/Mu\314\210nchen.jpg.1"
- "test_files/M\303\274nchen.jpg.1"

So, I would like to keep/track both files with same hash "768c2b350381b75dabd0c5f67741effbbcde61ed", manually track new files in git and use UTF-8 for your source code files.

Thanks again.
