### ISSUE TITLE
android ndk-build failed

### ISSUE THREAD

**Issue by zhumingxie** [OlehKulykov/PLzmaSDK#17]
Hi, android ndk-build failed:
jni/../../src/CPP/7zip/Common/FileStreams.cpp:554:27: error: use of undeclared identifier 'major'
          prop = (UInt32)(major(st.st_rdev)); //  + 1000);
                          ^
jni/../../src/CPP/7zip/Common/FileStreams.cpp:562:27: error: use of undeclared identifier 'minor'
          prop = (UInt32)(minor(st.st_rdev)); // + 100);
                          ^
2 errors generated.

I've tried plzmaSDK 1.2.2 and 1.2.3. And tried with several ndk-version, 
Did I miss something?

**Comment by OlehKulykov** [comment]
Hi, what OS type you are using?

**Comment by OlehKulykov** [comment]
Hi, the build issue fixed in ver. 1.2.4.
Thank you.
