### ISSUE TITLE
How to use multivolume archives

### ISSUE THREAD

**Issue by daiyangyang945** [OlehKulykov/PLzmaSDK#25]
I found that README mentioned the PLzmaSDK support 7z multivolume archives, but I don't know how to implement it. Can you give me some guidance

**Comment by OlehKulykov** [comment]
#### Extracting/decoding
1. Create array for adding InStreams.
2. For each archive part, create InStream(file | mem) and add to array from step 1.
3. Create InStream with array from step 1.
4. Create decoder with InStream from step 3.
5. Decode.

#### Compressing/encoding
1. Create OutMultiStream for archive parts and keep reference.
2. Create encoder with OutMultiStream from step 1.
3. Setup encoder, add files, set password etc.
4. Encode.
5. Take OutStreams array from OutMultiStream from step 1. Each OutStream in array is archive part.

#### Links
- C++: https://github.com/OlehKulykov/PLzmaSDK/blob/master/libplzma.hpp#L968C41-L968C41
- C: https://github.com/OlehKulykov/PLzmaSDK/blob/master/libplzma.h#L1388C51-L1388C51
- Swift: https://github.com/OlehKulykov/PLzmaSDK/blob/master/swift_pm_tests/plzmaTests/Compress.swift#L20
- C/C++: https://github.com/OlehKulykov/PLzmaSDK/blob/master/cmake_tests/test_plzma_multivolume.cpp#L64
- JS: https://github.com/OlehKulykov/PLzmaSDK/blob/master/node_tests/tests.js#L318C16-L318C16

**Comment by daiyangyang945** [comment]
thanks
