### ISSUE TITLE
mingw Support

### ISSUE THREAD

**Issue by yaobiao131** [OlehKulykov/PLzmaSDK#29]
can not compile success by mingw in windows,could you support it

**Comment by OlehKulykov** [comment]
MinGW, on Windows? Is it still alive?

Why not install Visual Studio - it's free nowadays?

**Comment by yaobiao131** [comment]
Some libraries can only be used in mingw. When mixing the two, only mingw can be used. And this library should work in mingw, but the macro definition needs to be modified. I added a mingw test here and it works normally.

**Comment by OlehKulykov** [comment]
Hi,
you can use version 1.4.5. 
Check README.md(CMake Windows(MinGW) section) or [CMake MinGW action](https://github.com/OlehKulykov/PLzmaSDK/actions/runs/10153334357/job/28076458690)

**Comment by yaobiao131** [comment]
thanks,i will try it
