### ISSUE TITLE
Multiple commands produce PrivacyInfo.xcprivacy

### ISSUE THREAD

**Issue by jxd524** [OlehKulykov/PLzmaSDK#33]
Hi

When the PrivacyInfo.xcpricacy file is present in the project,

pod 'PLzmaSDK-ObjC', '1.4.7'

The project will report an error with Multiple commands produce PrivacyInfo.xcprivacy

Cloud you  fix the resources of PLzmaSDK-ObjC.podspec

What I meant is [resource_bundles](https://guides.cocoapods.org/syntax/podspec.html#resource_bundles).This description refers to this type of problem.

I saw the usage of resource_bundles e.g. in the [lottie-ios podspec](https://github.com/airbnb/lottie-ios/blob/d4b75a089ef42d7c7db094671632aa311cbe1d83/lottie-ios.podspec#L31). That's why I mentioned this as a possible solution.

Thank you

**Comment by OlehKulykov** [comment]
Good morning,
thank you for the info. The next version(1.4.8) is available.

**Comment by jxd524** [comment]
You should delete
 s.resource = 'resources/PrivacyInfo.xcprivacy'
 
1.4.8 Still report the same error

**Comment by jxd524** [comment]
Hi

1.4.8 Still report the same error

You should delete

 s.resource = 'resources/PrivacyInfo.xcprivacy'

**Comment by jxd524** [comment]
You should delete
 s.resource = 'resources/PrivacyInfo.xcprivacy'
 
1.4.8 Still report the same error


 

> Good morning, thank you for the info. The next version(1.4.8) is available.

**Comment by OlehKulykov** [comment]
Hi, take a look into 1.4.9. Is it works for you?

**Comment by jxd524** [comment]
Hi

Thank you . It work!

But, there is a warning

￼


Ld /Users/terry/Library/Developer/Xcode/DerivedData/iReadNote-drobuqywanzuigdhieflontqeogl/Build/Products/Debug-iphonesimulator/iReadNote.app/iReadNote normal (in target 'iReadNote' from project 'iReadNote')
    cd /Users/terry/work/terry/iReadNote
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -Xlinker -reproducible -target arm64-apple-ios13.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.1.sdk -O0 -L/Users/terry/Library/Developer/Xcode/DerivedData/iReadNote-drobuqywanzuigdhieflontqeogl/Build/Intermediates.noindex/EagerLinkingTBDs/Debug-iphonesimulator -L/Users/terry/Library/Developer/Xcode/DerivedData/iReadNote-drobuqywanzuigdhieflontqeogl/Build/Products/Debug-iphonesimulator -L/Users/terry/Library/Developer/Xcode/DerivedData/iReadNote-drobuqywanzuigdhieflontqeogl/Build/Products/Debug-iphonesimulator/PLzmaSDK-ObjC -L/Users/terry/Library/Developer/Xcode/DerivedData/iReadNote-drobuqywanzuigdhieflontqeogl/Build/Products/Debug-iphonesimulator/UnrarKit -F/Users/terry/Library/Developer/Xcode/DerivedData/iReadNote-drobuqywanzuigdhieflontqeogl/Build/Intermediates.noindex/EagerLinkingTBDs/Debug-iphonesimulator -F/Users/terry/Library/Developer/Xcode/DerivedData/iReadNote-drobuqywanzuigdhieflontqeogl/Build/Products/Debug-iphonesimulator -filelist /Users/terry/Library/Developer/Xcode/DerivedData/iReadNote-drobuqywanzuigdhieflontqeogl/Build/Intermediates.noindex/iReadNote.build/Debug-iphonesimulator/iReadNote.build/Objects-normal/arm64/iReadNote.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/terry/Library/Developer/Xcode/DerivedData/iReadNote-drobuqywanzuigdhieflontqeogl/Build/Intermediates.noindex/iReadNote.build/Debug-iphonesimulator/iReadNote.build/Objects-normal/arm64/iReadNote_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -stdlib\=libc++ -fobjc-arc -fobjc-link-runtime -ObjC -lPLzmaSDK-ObjC -lUnrarKit -lc++ -lz -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/terry/Library/Developer/Xcode/DerivedData/iReadNote-drobuqywanzuigdhieflontqeogl/Build/Intermediates.noindex/iReadNote.build/Debug-iphonesimulator/iReadNote.build/iReadNote.app-Simulated.xcent -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __ents_der -Xlinker /Users/terry/Library/Developer/Xcode/DerivedData/iReadNote-drobuqywanzuigdhieflontqeogl/Build/Intermediates.noindex/iReadNote.build/Debug-iphonesimulator/iReadNote.build/iReadNote.app-Simulated.xcent.der -lPods-iReadNote -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/terry/Library/Developer/Xcode/DerivedData/iReadNote-drobuqywanzuigdhieflontqeogl/Build/Intermediates.noindex/iReadNote.build/Debug-iphonesimulator/iReadNote.build/Objects-normal/arm64/iReadNote_dependency_info.dat -o /Users/terry/Library/Developer/Xcode/DerivedData/iReadNote-drobuqywanzuigdhieflontqeogl/Build/Products/Debug-iphonesimulator/iReadNote.app/iReadNote

I really want to get rid of the warning message but don't know how to fix it, do you have any good suggestions?
