### ISSUE TITLE
Does this sdk support  7z multi-volume archives on the mobile devices？

### ISSUE THREAD

**Issue by freddiezhao** [OlehKulykov/PLzmaSDK#5]
Does this sdk support  7z multi-volume archives on the mobile devices？

hope receive you feedback

**Comment by OlehKulykov** [comment]
Hi, 
no, this sdk doesn't support multi-volumes.

**Comment by freddiezhao** [comment]
> Hi,
> no, this sdk doesn't support multi-volumes.

Got it， thanks
