### ISSUE TITLE
encoder.setPassword is not working

### ISSUE THREAD

**Issue by ghost** [OlehKulykov/PLzmaSDK#6]
I used the method in the demo to set the password and compressed it successfully. But when I uncompressed the file, I did not need to enter a password to uncompress it.

**Comment by OlehKulykov** [comment]
Are you using 'setShouldEncryptHeader' and or 'setShouldEncryptContent' with 'true' ?

**Comment by ghost** [comment]
Yeah, just like in the demo.
```
if let psd = password {
     try encoder.setPassword(psd)
     try encoder.setShouldEncryptHeader(true)
     try encoder.setShouldEncryptContent(true)
}
```

**Comment by OlehKulykov** [comment]
Which format are you using for compressing, 7z? 
Keep in mind, that currently supported xz and tar formats are doesn't support password protection.
Also, I've made a small test app.
[TestPLzmaSDKPod.zip](https://github.com/OlehKulykov/PLzmaSDK/files/6234838/TestPLzmaSDKPod.zip)
Please check it.

Also, provide your implementation.

**Comment by ghost** [comment]
Thank you very much for your test app! 
After I copied it to my project, it still didn't work. Then I found out that the version of the library I was using was too old. It's OK after the update!

**Comment by OlehKulykov** [comment]
It's a good news. 
And thank you for the use-case. I will add a public version property in a next major release(multivolume support).
