### ISSUE TITLE
Build issues in Catalina with Xcode 12

### ISSUE THREAD

**Issue by zcream** [OlehKulykov/PLzmaSDK#8]
I imported the Swift package using the git url -
`https://github.com/OlehKulykov/PLzmaSDK.git`

 I get this build error - 
`The package product 'PLzmaSDK-Static' cannot be used as a dependency of this target because it uses unsafe build flags.`

Xcode 12.4 and Catalina 10.15.7

**Comment by tbaranes** [comment]
I ran in the same issue, I opened a [pull request](https://github.com/OlehKulykov/PLzmaSDK/pull/7) to resolve this but got no news yet

**Comment by zcream** [comment]
@tbaranes I deleted that line and it is no longer giving that error. Now I get a bunch of errors about 
`plzma_in_stream archiveDataInStream = plzma_in_stream_create_with_memory_copy(<FILE DATA>, <FILE SIZE>); `

and

`plzma_decoder_set_progress_delegate_utf8_callback(&decoder, <UTF8 C CALLBACK>);`

What do we supply for FILE DATA, FILE SIZE and CALLBACK ?

**Comment by tbaranes** [comment]
Can't help you more, removing this line was enough for me, sorry 😅

**Comment by zcream** [comment]
Thanks for your help. Anyone else have working decompression code for C or  C++ ?

**Comment by OlehKulykov** [comment]
Check version 1.1.1
